spring.application.name=TIENDA_BRYAN_CASTANO_SANSEGUNDO

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.chat.model=gpt-3.5-turbo
openai.api.key=${OPENAI_API_KEY}
